### ISSUE TITLE
Figure out install error

### ISSUE THREAD

**Issue by iafisher** [iafisher/hera-py#112]
```
$ pip3 install --install-option="--prefix='/home/courses/InstalledSW'" hera-py
/usr/local/lib/python3.5/dist-packages/pip/commands/install.py:194: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting hera-py
  Using cached https://files.pythonhosted.org/packages/e5/02/89dcd310a8c0e8b988645237c43201342fdb25c55291c76d22dba89c6b76/hera-py-0.5.2.tar.gz
Collecting typing==3.6.6 (from hera-py)
  Using cached https://files.pythonhosted.org/packages/bf/9b/2bf84e841575b633d8d91ad923e198a415e3901f228715524689495b4317/typing-3.6.6.tar.gz
Skipping bdist_wheel for hera-py, due to binaries being disabled for it.
Skipping bdist_wheel for typing, due to binaries being disabled for it.
Installing collected packages: typing, hera-py
  Running setup.py install for typing ... done
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_install.py", line 922, in install
    with open(inst_files_path, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: "'/home/courses/InstalledSW'/lib/python3.5/site-packages/typing-3.6.6-py3.5.egg-info/installed-files.txt"
```

**Comment by iafisher** [comment]
This might not be an error with hera-py
